name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  uuid: ^3.0.0
